/**
 * In-Memory Store for VIZ India Digital Expo
 */

export const initialBrands: any[] = [
  {
    _id: '65e000000000000000000001',
    slug: 'burger-blast',
    brandName: 'Burger Blast',
    tagline: 'India’s Fastest Growing Gourmet Smash Burger Franchise',
    description: 'Burger Blast delivers chef-crafted gourmet burgers, loaded fries, and signature shakes with automated cloud-assisted kitchen operations and 65%+ gross margins.',
    category: 'Food',
    subCategories: ['QSR', 'Fast Food', 'Burgers', 'Cafe'],
    logoUrl: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=300&h=300&fit=crop&crop=faces',
    bannerUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=1200&h=600&fit=crop',
    pitchVideoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-hands-preparing-a-tasty-burger-41132-large.mp4',
    galleryUrls: [
      'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=800&fit=crop',
      'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&fit=crop',
    ],
    brochurePdfUrl: 'https://vizexpo.in/brochures/burger-blast.pdf',
    verificationStatus: 'VERIFIED',
    verifiedAt: new Date().toISOString(),
    isFeatured: true,
    featuredRank: 1,
    investmentRange: { minINR: 3000000, maxINR: 4000000, displayString: '₹30L – ₹40L' },
    franchiseFeeINR: 500000,
    royaltyPercentage: 5,
    requiredAreaSqFt: { min: 800, max: 1200, displayString: '800 – 1200 sq.ft.' },
    businessModel: 'FOFO',
    estimatedROIHistoricalMonths: {
      min: 12,
      max: 18,
      disclaimer: 'Based on historical figures provided by brand. Actual results depend on location and management.',
    },
    targetExpansionCities: ['Chandigarh', 'Delhi NCR', 'Mohali', 'Ludhiana', 'Jaipur', 'Bangalore'],
    existingOutletsCount: 42,
    yearEstablished: 2019,
    supportOffered: {
      siteSelection: true,
      staffTraining: true,
      marketingSupport: true,
      interiorSetup: true,
      rawMaterialSupply: true,
      softwareBillingPOS: true,
    },
    subscription: { tier: 'PREMIUM_BOOTH', agreedSuccessFeePercentage: 3.0, isActive: true },
    aiBotSettings: { isEnabled: true, botName: 'BlastBot AI' },
  },
  {
    _id: '65e000000000000000000002',
    slug: 'chai-shai-express',
    brandName: 'Chai Shai Express',
    tagline: 'Authentic Kulhad Chai & Desi Snacks Cafe Chain',
    description: 'High-margin, low-capex desi tea cafe concept offering 20+ varieties of hand-brewed kulhad chai, bun maska, and street delicacies.',
    category: 'Food',
    subCategories: ['Cafe', 'Beverages', 'Tea & Coffee'],
    logoUrl: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=300&h=300&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=1200&h=600&fit=crop',
    pitchVideoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-pouring-hot-tea-in-a-cup-43180-large.mp4',
    galleryUrls: ['https://images.unsplash.com/photo-1561047029-3000c68339ca?w=800&fit=crop'],
    brochurePdfUrl: 'https://vizexpo.in/brochures/chai-shai.pdf',
    verificationStatus: 'VERIFIED',
    verifiedAt: new Date().toISOString(),
    isFeatured: true,
    featuredRank: 2,
    investmentRange: { minINR: 1000000, maxINR: 1800000, displayString: '₹10L – ₹18L' },
    franchiseFeeINR: 300000,
    royaltyPercentage: 4,
    requiredAreaSqFt: { min: 300, max: 600, displayString: '300 – 600 sq.ft.' },
    businessModel: 'FOFO',
    estimatedROIHistoricalMonths: { min: 9, max: 14, disclaimer: 'Based on brand estimates. Actual performance varies with footfall.' },
    targetExpansionCities: ['Chandigarh', 'Amritsar', 'Dehradun', 'Indore', 'Bhopal', 'Lucknow'],
    existingOutletsCount: 85,
    yearEstablished: 2017,
    supportOffered: { siteSelection: true, staffTraining: true, marketingSupport: true, interiorSetup: true, rawMaterialSupply: true, softwareBillingPOS: true },
    subscription: { tier: 'FEATURED', agreedSuccessFeePercentage: 3.0, isActive: true },
    aiBotSettings: { isEnabled: true, botName: 'Chai Mitra AI' },
  },
  {
    _id: '65e000000000000000000003',
    slug: 'voltcharge-ev-hub',
    brandName: 'VoltCharge EV Station',
    tagline: 'High-Yield Commercial EV Fast-Charging Infrastructure',
    description: 'Turnkey FOCO/FOFO EV charging hubs along highways and commercial plazas with 100% automated billing and zero day-to-day staff hassle.',
    category: 'EV',
    subCategories: ['CleanTech', 'Electric Mobility'],
    logoUrl: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=300&h=300&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1558441719-7561f5c6b453?w=1200&h=600&fit=crop',
    pitchVideoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-car-charging-at-an-electric-station-43093-large.mp4',
    galleryUrls: ['https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800&fit=crop'],
    brochurePdfUrl: 'https://vizexpo.in/brochures/voltcharge.pdf',
    verificationStatus: 'VERIFIED',
    verifiedAt: new Date().toISOString(),
    isFeatured: true,
    featuredRank: 3,
    investmentRange: { minINR: 2000000, maxINR: 3500000, displayString: '₹20L – ₹35L' },
    franchiseFeeINR: 400000,
    royaltyPercentage: 10,
    requiredAreaSqFt: { min: 600, max: 1200, displayString: '600 – 1200 sq.ft.' },
    businessModel: 'FOCO',
    estimatedROIHistoricalMonths: { min: 15, max: 22, disclaimer: 'Utilization rates depend on highway traffic.' },
    targetExpansionCities: ['Chandigarh', 'Delhi-Amritsar Highway', 'Jaipur', 'Pune'],
    existingOutletsCount: 54,
    yearEstablished: 2021,
    supportOffered: { siteSelection: true, staffTraining: false, marketingSupport: true, interiorSetup: true, rawMaterialSupply: true, softwareBillingPOS: true },
    subscription: { tier: 'PREMIUM_BOOTH', agreedSuccessFeePercentage: 3.0, isActive: true },
    aiBotSettings: { isEnabled: true, botName: 'Volt AI Guide' },
  },
  {
    _id: '65e000000000000000000004',
    slug: 'kidzone-preschool',
    brandName: 'KidZone Early Learning Academy',
    tagline: 'Premium STEM-Integrated Pre-School & Daycare Chain',
    description: 'Award-winning early childhood curriculum designed for holistic child development with smart interactive classrooms and high parental retention.',
    category: 'Education',
    subCategories: ['Pre-School', 'Daycare'],
    logoUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=300&h=300&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1588072432836-e10032774350?w=1200&h=600&fit=crop',
    pitchVideoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-kids-playing-in-a-kindergarten-room-41908-large.mp4',
    galleryUrls: ['https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&fit=crop'],
    brochurePdfUrl: 'https://vizexpo.in/brochures/kidzone.pdf',
    verificationStatus: 'VERIFIED',
    verifiedAt: new Date().toISOString(),
    isFeatured: true,
    featuredRank: 4,
    investmentRange: { minINR: 3500000, maxINR: 6000000, displayString: '₹35L – ₹60L' },
    franchiseFeeINR: 600000,
    royaltyPercentage: 8,
    requiredAreaSqFt: { min: 2500, max: 4000, displayString: '2500 – 4000 sq.ft.' },
    businessModel: 'FOFO',
    estimatedROIHistoricalMonths: { min: 18, max: 24, disclaimer: 'Admissions and revenue depend on local demographic.' },
    targetExpansionCities: ['Chandigarh', 'Gurgaon', 'Noida', 'Ludhiana', 'Ahmedabad'],
    existingOutletsCount: 28,
    yearEstablished: 2016,
    supportOffered: { siteSelection: true, staffTraining: true, marketingSupport: true, interiorSetup: true, rawMaterialSupply: true, softwareBillingPOS: true },
    subscription: { tier: 'FEATURED', agreedSuccessFeePercentage: 3.0, isActive: true },
    aiBotSettings: { isEnabled: true, botName: 'KidZone Advisor AI' },
  },
  {
    _id: '65e000000000000000000005',
    slug: 'fitpulse-247-gym',
    brandName: 'FitPulse 24/7 Smart Gym',
    tagline: 'Tech-Driven 24-Hour Fitness Club Franchise',
    description: 'Biometric RFID access, state-of-the-art biomechanical equipment, and hybrid virtual coaching that minimizes front-desk overhead.',
    category: 'Fitness',
    subCategories: ['Gym', 'Wellness'],
    logoUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=300&h=300&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=1200&h=600&fit=crop',
    pitchVideoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-young-man-training-at-a-gym-41380-large.mp4',
    galleryUrls: ['https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800&fit=crop'],
    brochurePdfUrl: 'https://vizexpo.in/brochures/fitpulse.pdf',
    verificationStatus: 'VERIFIED',
    verifiedAt: new Date().toISOString(),
    isFeatured: false,
    featuredRank: 5,
    investmentRange: { minINR: 4500000, maxINR: 8000000, displayString: '₹45L – ₹80L' },
    franchiseFeeINR: 800000,
    royaltyPercentage: 6,
    requiredAreaSqFt: { min: 3000, max: 5000, displayString: '3000 – 5000 sq.ft.' },
    businessModel: 'FOFO',
    estimatedROIHistoricalMonths: { min: 14, max: 20, disclaimer: 'Membership presales determine actual ROI.' },
    targetExpansionCities: ['Chandigarh', 'Mohali', 'Panchkula', 'Zirakpur', 'Delhi'],
    existingOutletsCount: 19,
    yearEstablished: 2020,
    supportOffered: { siteSelection: true, staffTraining: true, marketingSupport: true, interiorSetup: true, rawMaterialSupply: false, softwareBillingPOS: true },
    subscription: { tier: 'BASIC', agreedSuccessFeePercentage: 3.0, isActive: true },
    aiBotSettings: { isEnabled: true, botName: 'Pulse AI' },
  },
  {
    _id: '65e000000000000000000006',
    slug: 'glowup-luxury-salon',
    brandName: 'GlowUp Salon & Spa',
    tagline: 'High-Ticket Hair, Skin & Bridal Salon Chain',
    description: 'Luxury salon chain offering premium hair styling, clinical aesthetic treatments, and bridal studio services.',
    category: 'Beauty',
    subCategories: ['Salon', 'Spa'],
    logoUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=300&h=300&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=1200&h=600&fit=crop',
    pitchVideoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-hairdresser-styling-hair-for-a-woman-42099-large.mp4',
    galleryUrls: ['https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=800&fit=crop'],
    brochurePdfUrl: 'https://vizexpo.in/brochures/glowup.pdf',
    verificationStatus: 'VERIFIED',
    verifiedAt: new Date().toISOString(),
    isFeatured: false,
    featuredRank: 6,
    investmentRange: { minINR: 2500000, maxINR: 4500000, displayString: '₹25L – ₹45L' },
    franchiseFeeINR: 500000,
    royaltyPercentage: 7,
    requiredAreaSqFt: { min: 1200, max: 1800, displayString: '1200 – 1800 sq.ft.' },
    businessModel: 'FOFO',
    estimatedROIHistoricalMonths: { min: 12, max: 16, disclaimer: 'Based on average ticket size and stylist utilization.' },
    targetExpansionCities: ['Chandigarh', 'Ludhiana', 'Jalandhar', 'Shimla', 'Jaipur'],
    existingOutletsCount: 15,
    yearEstablished: 2018,
    supportOffered: { siteSelection: true, staffTraining: true, marketingSupport: true, interiorSetup: true, rawMaterialSupply: true, softwareBillingPOS: true },
    subscription: { tier: 'BASIC', agreedSuccessFeePercentage: 3.0, isActive: true },
    aiBotSettings: { isEnabled: true, botName: 'Glow AI' },
  },
];

export const initialUsers: any[] = [
  {
    _id: '65e100000000000000000001',
    name: 'Rohit Sharma',
    email: 'rohit.sharma@gmail.com',
    phone: '+91 98888 12345',
    role: 'INVESTOR',
    isPhoneVerified: true,
    isEmailVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&h=150&fit=crop&crop=faces',
    investorProfileId: '65e200000000000000000001',
  },
  {
    _id: '65e100000000000000000002',
    name: 'Vikram Sethi (Brand Head)',
    email: 'franchise@burgerblast.in',
    phone: '+91 98111 22334',
    role: 'BRAND_ADMIN',
    brandId: '65e000000000000000000001',
    isPhoneVerified: true,
    isEmailVerified: true,
  },
  {
    _id: '65e100000000000000000003',
    name: 'VIZ Operational Admin',
    email: 'admin@vizexpo.in',
    phone: '+91 99999 00000',
    role: 'VIZ_ADMIN',
    isPhoneVerified: true,
    isEmailVerified: true,
  },
];

export const initialInvestorProfiles: any[] = [
  {
    _id: '65e200000000000000000001',
    userId: '65e100000000000000000001',
    city: 'Chandigarh',
    state: 'Punjab',
    tier: 'TIER_2',
    investmentBudget: { minINR: 2500000, maxINR: 5000000, bracket: '25L_50L' },
    preferredCategories: ['Food', 'EV', 'Retail'],
    franchiseModelPreference: ['FOFO'],
    businessExperienceYears: 4,
    availableCommercialSpaceSqFt: 1000,
    savedBrandIds: ['65e000000000000000000001'],
    subscription: { plan: 'FREE', directMeetingCreditsRemaining: 5, aiQueryCreditsRemaining: 50 },
  },
];

export const initialLeads: any[] = [
  {
    _id: '65e300000000000000000001',
    investorId: initialUsers[0],
    brandId: initialBrands[0],
    source: 'BOOTH_DISCOVERY',
    status: 'MEETING_SCHEDULED',
    investorSnapshot: {
      name: 'Rohit Sharma',
      phone: '+91 98888 12345',
      email: 'rohit.sharma@gmail.com',
      city: 'Chandigarh',
      budgetBracket: '₹25L – ₹50L',
      experienceYears: 4,
    },
    brandInternalNotes: ['High intent franchisee from Sector 35 Chandigarh. Ready commercial space available.'],
    dealValueEstimatedINR: 3500000,
    stageHistory: [
      { stage: 'NEW', updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), note: 'Discovered on floor' },
      { stage: 'MEETING_SCHEDULED', updatedAt: new Date().toISOString(), note: 'Scheduled video discovery call' },
    ],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const initialMeetings: any[] = [
  {
    _id: '65e400000000000000000001',
    leadId: '65e300000000000000000001',
    investorId: initialUsers[0],
    brandId: initialBrands[0],
    scheduledStartTime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    scheduledEndTime: new Date(Date.now() + 2.5 * 60 * 60 * 1000).toISOString(),
    meetingType: 'VIDEO_CALL',
    status: 'ACCEPTED',
    meetingRoomUrl: 'https://meet.vizexpo.in/room-bb-chandigarh-982',
    notesFromInvestor: 'Finalize FOFO unit economics, royalty terms, and exclusive radius in Chandigarh.',
    createdAt: new Date().toISOString(),
  },
];

export const initialDeals: any[] = [
  {
    _id: '65e500000000000000000001',
    dealNumber: 'VIZ-DEAL-2026-0001',
    brandId: initialBrands[0],
    investorId: initialUsers[0],
    franchiseCity: 'Chandigarh',
    franchiseUnitModel: 'FOFO',
    totalDealValueINR: 3000000,
    commissionRatePercentage: 3.0,
    calculatedCommissionINR: 90000,
    taxINR: 16200,
    totalInvoiceAmountINR: 106200,
    status: 'RECEIVED_SETTLED',
    invoiceNumber: 'VIZ-INV-2026-0001',
    paymentReferenceNo: 'HDFC-RTGS-99281726',
    settledAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    brandNotes: 'Agreement executed for Sector 35 Chandigarh outlet.',
    adminNotes: '3% VIZ success fee verified and settled into VIZ bank account.',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const initialKnowledgeBases: any[] = [
  {
    _id: '65e600000000000000000001',
    brandId: '65e000000000000000000001',
    sourceType: 'FINANCIAL_BREAKUP',
    title: 'Total Investment & Fee Breakup',
    question: 'Is franchise ka total investment kitna hai?',
    answer: 'Brand-provided information ke according total estimated investment ₹30–40 lakh hai. Isme ₹5 Lakh franchise fee, ₹18–22 Lakh kitchen machinery & automated griddles, aur ₹8–12 Lakh modern interior fit-out shamil hai.',
    content: 'Total capital requirement ₹30-40 Lakh for 800-1200 sqft outlet under FOFO format.',
    isApprovedByBrand: true,
    isApprovedByAdmin: true,
  },
];

class MemoryStore {
  brands: any[] = [...initialBrands];
  users: any[] = [...initialUsers];
  investorProfiles: any[] = [...initialInvestorProfiles];
  knowledgeBases: any[] = [...initialKnowledgeBases];
  leads: any[] = [...initialLeads];
  meetings: any[] = [...initialMeetings];
  deals: any[] = [...initialDeals];
}

export const inMemoryStore = new MemoryStore();
